export const EMAIL = 'EMAIL'
export const ERROR_STATE = 'ERROR_STATE'
export const IS_AUTH = 'IS_AUTH'
export const NICKNAME = 'NICKNAME'
export const USERNUM = 'USERNUM'
export const CLS = 'CLS'
export const LESSONS = 'LESSONS'